name: 'ecommerce_dw'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dw:
    +quoting:
      identifier: false
    staging:
      +materialized: view
      +schema: staging
    marts:
      core:
        +materialized: table
        +schema: core
      finance:
        +materialized: table
        +schema: finance

vars:
  start_date: '2020-01-01'
  end_date: '2024-12-31'

on-run-start:
  - "USE WAREHOUSE {{ target.warehouse }}"
  - "USE DATABASE {{ target.database }}"

on-run-end:
  - '{{ log("dbt run completed successfully!", info=True) }}'