-- Snowflake Data Warehouse Setup

-- Create database and schemas
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DW;
USE DATABASE ECOMMERCE_DW;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS FINANCE;

-- Create warehouse for compute
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create role for dbt transformations
CREATE ROLE IF NOT EXISTS TRANSFORMER;

-- Grant permissions
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ECOMMERCE_DW TO ROLE TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_DW TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE ECOMMERCE_DW TO ROLE TRANSFORMER;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE ECOMMERCE_DW TO ROLE TRANSFORMER;

-- Grant role to user (replace with your username)
GRANT ROLE TRANSFORMER TO USER YOUR_USERNAME;

-- Set default role and warehouse
ALTER USER YOUR_USERNAME SET DEFAULT_ROLE = TRANSFORMER;
ALTER USER YOUR_USERNAME SET DEFAULT_WAREHOUSE = COMPUTE_WH;

-- Enable query tagging for monitoring
ALTER SESSION SET QUERY_TAG = 'dbt_ecommerce_setup';