version: 2

sources:
  - name: snow
    description: Snowflake staging schema with data loaded from PostgreSQL
    database: ECOMMERCE_DW
    schema: PUBLIC
    tables:
      - name: customers
        description: Customer information from PostgreSQL
        columns:
          - name: customer_id
            description: Unique customer identifier
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - unique
              - not_null
          - name: first_name
            tests:
              - not_null
          - name: last_name
            tests:
              - not_null
              
      - name: products
        description: Product catalog from PostgreSQL
        columns:
          - name: product_id
            description: Unique product identifier
            tests:
              - unique
              - not_null
          - name: product_name
            tests:
              - not_null
          - name: unit_price
            description: Product unit price
            tests:
              - not_null
          - name: cost_price
            tests:
              - not_null
              
      - name: orders
        description: Order transactions from PostgreSQL
        columns:
          - name: order_id
            description: Unique order identifier
            tests:
              - not_null
          - name: customer_id
            description: Reference to customer
            tests:
              - not_null
              - relationships:
                  to: source('staging', 'customers')
                  field: customer_id
          - name: product_id
            description: Reference to product
            tests:
              - not_null
              - relationships:
                  to: source('staging', 'products')
                  field: product_id
          - name: total_amount
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null

models:
  - name: stg_customers
    description: Cleaned and standardized customer data
    columns:
      - name: customer_key
        description: Surrogate key for customer
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Natural key from source system
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email address
        tests:
          - unique
          - not_null

  - name: stg_products
    description: Cleaned and standardized product data
    columns:
      - name: product_key
        description: Surrogate key for product
        tests:
          - unique
          - not_null
      - name: product_id
        description: Natural key from source system
        tests:
          - unique
          - not_null
      - name: unit_price
        description: Product unit price
        tests:
          - not_null

  - name: stg_orders
    description: Cleaned and standardized order data
    columns:
      - name: order_key
        description: Surrogate key for order
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null

  - name: dim_customers
    description: Customer dimension table
    columns:
      - name: customer_key
        description: Surrogate key for customer
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Natural key from source system
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email address
        tests:
          - unique
          - not_null

  - name: dim_products
    description: Product dimension table
    columns:
      - name: product_key
        description: Surrogate key for product
        tests:
          - unique
          - not_null
      - name: product_id
        description: Natural key from source system
        tests:
          - unique
          - not_null
      - name: unit_price
        description: Product unit price
        tests:
          - not_null

  - name: dim_dates
    description: Date dimension table
    columns:
      - name: date_key
        description: Surrogate key for date
        tests:
          - unique
          - not_null
      - name: full_date
        description: Full date value
        tests:
          - unique
          - not_null

  - name: fact_orders
    description: Order fact table
    columns:
      - name: order_key
        description: Surrogate key for order
        tests:
          - unique
          - not_null
      - name: customer_key
        description: Foreign key to customer dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
      - name: product_key
        description: Foreign key to product dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_key
      - name: date_key
        description: Foreign key to date dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: total_amount
        description: Total order amount
        tests:
          - not_null